### ISSUE TITLE
Ability to disable html parsing entirely

### ISSUE THREAD

**Issue by a1studmuffin** [Sommerregen/grav-plugin-textformatter#1]
Awesome plugin! One issue I have though is that I'd like to disable the HTML comments processing entirely. I see for most of the other processing types (eg. fancypants, escaper etc.) there is an overall enable/disable toggle, but for the html section there's just sub-options to turn on/off comments/entities/elements. Thanks :)

**Comment by Sommerregen** [comment]
This is because the HTML section uses several formatter, whereas the other processing types (eg. fancypants, escaper etc.) only uses one formatter. However I will mark it as enhancement and will come to this, when there is more time than now.

**Comment by Sommerregen** [comment]
Hi @a1studmuffin,

in the develop branch you will find a sneak peek of the upcoming version. It includes your request; you can now set `html.enabled: false` to disable the html parser completely. And you can enable it with `html.enabled: true`.

Before I'll release a new version, I'll tweak the code further. The vendor libs are already updated, but I'll re-arrange the config settings into tabs and fix some more bugs.

FYI the next version will contain a **breaking change**: the option `process` will be renamed to `active`, which makes more sense in its action.

**Comment by Sommerregen** [comment]
Hi @a1studmuffin, I just released **TextFormatter v1.1.0** with lots of improvements. Check it out :smile: .

Cheers!

**Comment by a1studmuffin** [comment]
Thanks a lot! :+1:
