### ISSUE TITLE
InvalidArgumentException - Invalid resource http://

### ISSUE THREAD

**Issue by LostInInaka** [Sommerregen/grav-plugin-textformatter#2]
Just updated this extension and noticed a few major problems
1. After running the extension, I am hit with a 
   
   ```
    [InvalidArgumentException]
    Invalid resource http://
   ```

from

```
/var/www/public_html/classes/thesis/vendor/rockettheme/toolbox/ResourceLocator/
src/UniformResourceLocator.php
```

on line 396 (middle line below)

```
        if (!isset($this->schemes[$scheme])) {
            throw new \InvalidArgumentException("Invalid resource {$scheme}://");
        }
```

after installed from a command line interface or when trying to load from a front-facing page
1. After install, it makes the web admin interface appear to have no themes or plugins installed. 

Both of these issues are remedied by removing the plugin, then everything works as normal.

This error repeatable both via admin interface and command line, and both with and without additional plugins being installed

**Comment by Sommerregen** [comment]
Hi @LostInInaka , that is something new. Unfortunately I can't reproduce it. Can you show me the full stacktrace? Which Grav version are you using + admin? How does your `textformatter.yaml` looks like (either in `user/plugins` or in plugin directory)?  Does it happens on a fresh Grav install? 

There are only a few places, where I'm using the ResourceLocator, one is [here](https://github.com/Sommerregen/grav-plugin-textformatter/blob/develop/textformatter.php#L188-L193) and [here](https://github.com/Sommerregen/grav-plugin-textformatter/blob/develop/classes/TextFormatter.php#L100-L102). Both use the option `emoticons.path`, which must be a local path. An external path starting with `http://` may cause this issue. By default this option is empty and refers to a local path `user://assets/emoticons`.

**Comment by LostInInaka** [comment]
Thanks for your reply @Sommerregen !

I figured out what the problem was...I had a leftover `textformatter.yaml` from a previous install, and it was trying to find a location that no longer existed, thus was throwing the exception.  Once I removed the old file it started working perfectly!

Thanks for the hint about asking me what the yaml file looked like - made me remember the one kept in the user/config/plugins directory ;)
