### ISSUE TITLE
Crashes site after latest update

### ISSUE THREAD

**Issue by 2braincells2go** [Sommerregen/grav-plugin-textformatter#4]
After updating site to latest (everything), textformatter crashes site and have to disable.

All plugins listed below and running gravstrap theme.

![image](https://cloud.githubusercontent.com/assets/2567500/17915985/bc80aeda-6974-11e6-93fa-b326dbc85bea.png)

 Admin Panel  v1.1.4
 Archives  v1.5.0
 Assets  v1.2.1
 BlogInjector v1.2.3
 Bootstrapper  v1.3.2
 Breadcrumbs  v1.5.0
 Custom CSS  v0.2.1
 Editor Buttons  v1.1.1
 Email  v2.4.3
 Error  v1.5.1
 External Links v1.4.2
 Feed  v1.5.0
 Form  v1.3.2
 Gravstrap v1.2.2
 Highlight  v1.3.1
 LangSwitcher  v1.2.1
 Login  v2.0.1
 Markdown Color  v1.0.1
 Markdown Notices  v1.0.0
 Markdown Sections v0.9.1
 Mini Code v1.1.0
 Pagination  v1.3.2
 Problems  v1.4.3
 Random  v1.5.0
 Related Pages  v1.1.4
 Shortcode Core  v2.3.1
 SimpleSearch  v1.8.0
 SocialButtons v1.0.3
 Taxonomy List  v1.2.7
 Text Formatter v1.1.0
 Themer v1.1.0
 YouTube  v2.0.2

**Comment by Sommerregen** [comment]
@2braincells2go That's maybe related to #1. Thanks for the stack-trace. Can you also copy and paste you markdown content here? MediaEmebd seems to crash. Thanks, in advance! Will dig into it on weekend.

**Comment by 2braincells2go** [comment]
Thanks for update!

Are you asking for the actual markdown code for the front page of site?

The markdown is basically copied directly from grav-strap default setup. just modified your example pages. Be happy to paste here but want to make sure what you are asking for.

Cheers!

**Comment by Sommerregen** [comment]
Hi @2braincells2go , yes I'm interested in the markdown code. The best is also to print the plugins (with versions) you are using (or to recreate the issue). Maybe there is one hidden interference, I haven't considered yet.

**Comment by Sommerregen** [comment]
Hi @2braincells2go  ,

I tested my plugin against the Grav Schortcode Core plugin after I have done some changes. At least for me TextFormatter doesn't interfere right now with the Grav Schortcode Core plugin anymore. I released a testing version. Can you check whether these changes solves your issue?

**Comment by 2braincells2go** [comment]
Hey Benny. Sorry for disappearing and not responding. Little home accident and messed my back up so been out of commission.

I will give the testing version a try tonight or morning and let you know.

Thanks!

**Comment by 2braincells2go** [comment]
Able to sit in chair for few hours so gave the new test version a try, no go. Produces the same error.

Rather not post all our site info here in public area. Not sure anything that could be used to cause problems, but, not willing to take that chance. Do you have email address or some pother place for me to post the complete error dump and markup?

Thanks!

**Comment by Sommerregen** [comment]
Hi @2braincells2go ,

alright. You can either contact me privately in Gitter (click on my icon and click on "Chat privately") or you can send me a link to the file to my email address sommerregen@benjamin-regler.de .

The best is to give me the smallest working example as you can; maybe textformatter with shortcode-core plugin, the file in the pages folder, which creates the problem and the `user/config` folder. All other stuff should be irrelevant. But try it beforehand. Otherwise send me the whole package and I will do it for you.

Thanks in advance!

**Comment by Sommerregen** [comment]
I cannot recreate the issue. Will close it due to inactivity. Feel free to open it again.

**Comment by 2braincells2go** [comment]
Sorry for lack of response. Sadly we had to move back to chunky WordPress. The younger kids could not get a handle on the editor and updates were just too confusing for them. I spent more time troubleshooting things and time is something do not have much of:)

Thank you for your time.

**Comment by Sommerregen** [comment]
Ok, thanks for your update. I totally understand your point. I wish you all the best!
